/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.examen_1_243566.Vista;

import com.examen_1_243566.Modelo.Paciente;
import com.examen_1_243566.Sistema.SistemaCitas;
import javax.swing.JOptionPane;
import com.examen_1_243566.Vista.FrmSeleccionarMedico;

/**
 *
 * @author Adria
 */
public class FrmIngresarNSS extends javax.swing.JFrame {

    
    private SistemaCitas sistema;
    
    /**
     * Creates new form FrmIngresarNSS
     */
    public FrmIngresarNSS(SistemaCitas sistema) {
        initComponents();
        this.sistema = sistema;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtIngresaNSS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnIngresarNSS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtIngresaNSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIngresaNSSActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Numero de Seguro Social(NSS):");

        BtnIngresarNSS.setText("Ingresar");
        BtnIngresarNSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarNSSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TxtIngresaNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnIngresarNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtIngresaNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BtnIngresarNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void TxtIngresaNSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIngresaNSSActionPerformed
        
    }//GEN-LAST:event_TxtIngresaNSSActionPerformed

    private void BtnIngresarNSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarNSSActionPerformed
        String nss = TxtIngresaNSS.getText().trim(); // Obtiene el texto sin espacios extra

    // Este IF Valida
    if (nss.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Por favor, ingrese su Número de Seguridad Social (NSS).",
                "Campo vacío",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Busca
    Paciente paciente = sistema.buscarPaciente(nss);

    // Si no encuentra avisa
    if (paciente == null) {
        JOptionPane.showMessageDialog(this,
                "❌ NSS no encontrado.\nVerifique que esté correctamente escrito e intente de nuevo.",
                "NSS incorrecto",
                JOptionPane.ERROR_MESSAGE);

        TxtIngresaNSS.setText(""); // Limpia 
        TxtIngresaNSS.requestFocus(); 
        return;
    }

    // Si existe. adelante
    JOptionPane.showMessageDialog(this,
            "✅ Paciente encontrado:\n" + paciente.getNombre(),
            "Validación exitosa",
            JOptionPane.INFORMATION_MESSAGE);
    
    FrmSeleccionarMedico frmMedico = new FrmSeleccionarMedico(sistema, paciente, nss);
    frmMedico.setVisible(true);
    this.dispose();
    
    
    }//GEN-LAST:event_BtnIngresarNSSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIngresarNSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIngresarNSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIngresarNSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIngresarNSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            SistemaCitas sistema = new SistemaCitas(); // crear sistema
            FrmIngresarNSS frmNSS = new FrmIngresarNSS(sistema); // pasar sistema al constructor
            frmNSS.setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresarNSS;
    private javax.swing.JTextField TxtIngresaNSS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
