/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.examen_1_243566.Vista;

import com.examen_1_243566.Modelo.Medico;
import com.examen_1_243566.Modelo.Paciente;
import com.examen_1_243566.Sistema.SistemaCitas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adria
 */
public class FrmSeleccionarMedico extends javax.swing.JFrame {

    private SistemaCitas sistema;  
    private Paciente paciente;
    private String nss;
    
    
    /**
     * Creates new form FrmSeleccionarMedico
     */
    public FrmSeleccionarMedico(SistemaCitas sistema, Paciente paciente, String nss) {
   
        this.sistema = sistema;
        this.paciente = paciente;
        this.nss = nss;
        
        initComponents(); 
        lblTituloInformacion.setText("Información del Paciente");
        cargarDatosPaciente();
        cargarTablaMedicos();
        setLocationRelativeTo(null);
        BtnAñadirCita.setVisible(false);
        lblTituloNombreMedico.setVisible(false);
        lblTituloConsultorio.setVisible(false);
        lblTituloDiasYHoras.setVisible(false);
        lblDiasYHoras.setVisible(false);
        
    }
    private void cargarDatosPaciente() {
        if (paciente != null) {
        lblNombrePaciente1.setText(paciente.getNombre());
        lblNombrePaciente2.setText(paciente.getNombre());
        lblNSSPaciente.setText(paciente.getNss()); // si tu Paciente tiene método getNss()
        lblEdad.setText(String.valueOf(paciente.getEdad()));
        lblDomicilio.setText(paciente.getDomicilio());
        lblSeguro.setText(paciente.isTieneSeguro() ? "Sí" : "No");
        lblCURP.setText(paciente.getCurp());
        lblTipoSangre.setText(paciente.getTipoSangre());
    }
   }
    
    private void cargarTablaMedicos() {
    DefaultTableModel modelo = (DefaultTableModel) TbMedicos.getModel();
    modelo.setRowCount(0); // Limpia filas existentes

    for (Medico medico : sistema.obtenerMedicos()) {
        Object[] fila = new Object[] {
            medico.getNombre(),
            medico.getEspecialidad(),
            medico.getConsultorio()
        };
        modelo.addRow(fila);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNSSPaciente = new javax.swing.JLabel();
        lblNombrePaciente1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbMedicos = new javax.swing.JTable();
        BtnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTituloInformacion = new javax.swing.JLabel();
        lblTituloEdad = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblNombrePaciente2 = new javax.swing.JLabel();
        lblTituloSeguro = new javax.swing.JLabel();
        lblSeguro = new javax.swing.JLabel();
        lblCURP = new javax.swing.JLabel();
        lblTituloCurp = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        lblTituloDomicilio = new javax.swing.JLabel();
        lblTipoSangre = new javax.swing.JLabel();
        lblTituloTipoSangre = new javax.swing.JLabel();
        lblTituloNombreMedico = new javax.swing.JLabel();
        lblNombreMedico = new javax.swing.JLabel();
        lblTituloConsultorio = new javax.swing.JLabel();
        lblConsultorio = new javax.swing.JLabel();
        lblTituloDiasYHoras = new javax.swing.JLabel();
        lblDiasYHoras = new javax.swing.JLabel();
        BtnAñadirCita = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        lblNSSPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNombrePaciente1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        TbMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Especialidad", "Consultorio"
            }
        ));
        TbMedicos.setGridColor(new java.awt.Color(255, 255, 255));
        TbMedicos.setRowHeight(25);
        TbMedicos.setShowHorizontalLines(true);
        TbMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbMedicos);

        BtnSalir.setBackground(new java.awt.Color(255, 51, 51));
        BtnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloInformacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTituloInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTituloEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloEdad.setText("Edad:");

        lblEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloNombre.setText("Nombre del Paciente:");

        lblNombrePaciente2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTituloSeguro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloSeguro.setText("Seguro:");

        lblSeguro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblCURP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTituloCurp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloCurp.setText("CURP:");

        lblDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTituloDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloDomicilio.setText("Domicilio:");

        lblTipoSangre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTituloTipoSangre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloTipoSangre.setText("Tipo de Sangre:");

        lblTituloNombreMedico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloNombreMedico.setText("Nombre del Medico:");

        lblNombreMedico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTituloConsultorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloConsultorio.setText("Consultorio:");

        lblConsultorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTituloDiasYHoras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloDiasYHoras.setText("Dias y Horas:");

        lblDiasYHoras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloSeguro)
                    .addComponent(lblSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloNombre)
                    .addComponent(lblNombrePaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloEdad)
                            .addComponent(lblTituloCurp)
                            .addComponent(lblCURP, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloDomicilio))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloDiasYHoras)
                            .addComponent(lblConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloConsultorio)
                            .addComponent(lblTituloTipoSangre)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTituloNombreMedico)
                            .addComponent(lblNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiasYHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTituloNombre)
                        .addGap(6, 6, 6)
                        .addComponent(lblNombrePaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloEdad)
                            .addComponent(lblTituloTipoSangre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTituloSeguro))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTituloNombreMedico)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTituloCurp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCURP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTituloConsultorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloDomicilio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloDiasYHoras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDiasYHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        BtnAñadirCita.setBackground(new java.awt.Color(204, 255, 255));
        BtnAñadirCita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnAñadirCita.setText("Agendar Cita");
        BtnAñadirCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNSSPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(BtnAñadirCita, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lblNombrePaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(371, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblNSSPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAñadirCita, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(lblNombrePaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
    FrmIngresarNSS frmNSS = new FrmIngresarNSS(this.sistema);
    frmNSS.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void TbMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbMedicosMouseClicked
        int fila = TbMedicos.getSelectedRow();
        if (fila >= 0) {
        String nombre = TbMedicos.getValueAt(fila, 0).toString();

        // Buscar el objeto Medico por nombre
        Medico medicoSeleccionado = null;
        for (Medico m : sistema.obtenerMedicos()) {
            if (m.getNombre().equals(nombre)) {
                medicoSeleccionado = m;
                break;
            }
        }

        if (medicoSeleccionado != null) {
            
            lblTituloNombre.setText("Nombre del Medico:");
            lblTituloEdad.setText("Días Disponibles:");
            lblTituloSeguro.setText("Consultorio:");
            lblTituloCurp.setText("Horas Disponibles:");
            lblTituloInformacion.setText("Información del Medico");
            
            lblNombrePaciente2.setText(medicoSeleccionado.getNombre()); 
            lblEdad.setText(medicoSeleccionado.getDias()); 
            lblCURP.setText(medicoSeleccionado.getHoras()); 
            lblSeguro.setText(medicoSeleccionado.getConsultorio()); 
            
            lblConsultorio.setVisible(false);
            lblNombreMedico.setVisible(false);
            lblTituloNombreMedico.setVisible(false);
            lblTituloConsultorio.setVisible(false);
            lblDomicilio.setVisible(false);
            lblTituloDomicilio.setVisible(false);
            lblTipoSangre.setVisible(false);
            lblTituloTipoSangre.setVisible(false);
            lblTituloDiasYHoras.setVisible(false);
            lblDiasYHoras.setVisible(false);
            
            
            BtnAñadirCita.setVisible(true);
        }
      }
    }//GEN-LAST:event_TbMedicosMouseClicked

    private void BtnAñadirCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirCitaActionPerformed
        int fila = TbMedicos.getSelectedRow();
        if (fila >= 0) {
        String nombre = TbMedicos.getValueAt(fila, 0).toString();

        // Buscar el objeto Medico por nombre
        Medico medicoSeleccionado = null;
        for (Medico m : sistema.obtenerMedicos()) {
            if (m.getNombre().equals(nombre)) {
                medicoSeleccionado = m;
                break;
            }
        }
         
        cargarDatosPaciente();
        
        
        if (medicoSeleccionado != null) {
            
            lblTituloNombre.setText("Nombre del Paciente:");
            lblTituloEdad.setText("Edad:");
            lblTituloSeguro.setText("Seguro:");
            lblTituloCurp.setText("CURP:");           
            lblTituloInformacion.setText("Resumen");
            
            lblTituloNombreMedico.setVisible(true);
            lblTituloConsultorio.setVisible(true);
            lblDomicilio.setVisible(true);
            lblTituloDomicilio.setVisible(true);
            lblTipoSangre.setVisible(true);
            lblTituloTipoSangre.setVisible(true);
            lblConsultorio.setVisible(true);
            lblNombreMedico.setVisible(true);
            lblTituloDiasYHoras.setVisible(true);
            lblDiasYHoras.setVisible(true);
           
            lblNombreMedico.setText(medicoSeleccionado.getNombre()); 
            lblConsultorio.setText(medicoSeleccionado.getConsultorio());
            lblDiasYHoras.setText(medicoSeleccionado.getDias() + ", " + medicoSeleccionado.getHoras());
            
            JOptionPane.showMessageDialog(
            this,
            "✅ La cita con el Dr./Dra. " + medicoSeleccionado.getNombre() + " ha sido agendada correctamente.",
            "Cita confirmada",
            JOptionPane.INFORMATION_MESSAGE
        );
      
     } else {
    JOptionPane.showMessageDialog(
        this,
        "⚠️ Por favor selecciona un médico antes de continuar.",
        "Advertencia",
        JOptionPane.WARNING_MESSAGE
    );
            
        }
      }
        
        
    }//GEN-LAST:event_BtnAñadirCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAñadirCita;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTable TbMedicos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCURP;
    private javax.swing.JLabel lblConsultorio;
    private javax.swing.JLabel lblDiasYHoras;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNSSPaciente;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JLabel lblNombrePaciente1;
    private javax.swing.JLabel lblNombrePaciente2;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JLabel lblTipoSangre;
    private javax.swing.JLabel lblTituloConsultorio;
    private javax.swing.JLabel lblTituloCurp;
    private javax.swing.JLabel lblTituloDiasYHoras;
    private javax.swing.JLabel lblTituloDomicilio;
    private javax.swing.JLabel lblTituloEdad;
    private javax.swing.JLabel lblTituloInformacion;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloNombreMedico;
    private javax.swing.JLabel lblTituloSeguro;
    private javax.swing.JLabel lblTituloTipoSangre;
    // End of variables declaration//GEN-END:variables
}
